Repository projectsyn/component-rancher-monitoring, pull requests merged in 2021-05, with the labels that each got.

#18 Add GitHub action to generate Changelog entries for releases
  .github/PULL_REQUEST_TEMPLATE.md
  .github/changelog-configuration.json
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  CHANGELOG.md
  renovate.json
Labels: change

#19 Reimplement federation with Rancher Prometheus
  component/federation.jsonnet
  component/prometheus.jsonnet
Labels: change

#20 Make alert namespace selector configurable
  class/defaults.yml
  component/rules.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#17 Deduplicate NodeFilesystem* alerts when if device is mounted multiple times
  component/rules.jsonnet
Labels: fix

#21 Alertmanager: replace deprecated attributes
  component/alertmanager.jsonnet
Labels: bug, fix
