Repository projectsyn/component-rancher-monitoring, pull requests merged in 2022-03, with the labels that each got.

#61 Allow appending relabel configs to federation jobs
  class/defaults.yml
  component/federation.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#53 Update dependency quay.io/prometheus/alertmanager to v0.23.0
  class/defaults.yml
Labels: dependency

#54 chore(deps): update dependency quay.io/prometheus/prometheus to v2.34.0
  class/defaults.yml
  tests/golden/defaults/rancher-monitoring/rancher-monitoring/01_prometheus.yaml
  tests/golden/defaults/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.21/rancher-monitoring/rancher-monitoring/01_prometheus.yaml
  tests/golden/kubernetes-1.21/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
Labels: dependency

#63 Update modulesync config
  .sync.yml
Labels: ignore

#66 Fix wrong selector for alertmanager ServiceMonitor
  component/alertmanager.jsonnet
  tests/golden/defaults/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.21/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
Labels: bug

#67 Pin rancher-monitoring to v2
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/rancher-monitoring/rancher-monitoring/10_federation.yaml
  tests/golden/defaults/rancher-monitoring/rancher-monitoring/rules/00_kube-prometheus.yaml
  tests/golden/kubernetes-1.21/rancher-monitoring/rancher-monitoring/10_federation.yaml
  tests/golden/kubernetes-1.21/rancher-monitoring/rancher-monitoring/rules/00_kube-prometheus.yaml
Labels: breaking
