Repository projectsyn/component-rancher-monitoring, pull requests merged in 2022-09, with the labels that each got.

#81 Add support for K8s 1.23 and add missing tests for 1.22 and 1.23
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  tests/golden/kubernetes-1.22/rancher-monitoring/apps/rancher-monitoring.yaml
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/00_namespace.yaml
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/01_prometheus.yaml
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/10_federation.yaml
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/rules/00_kube-prometheus.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/apps/rancher-monitoring.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/00_namespace.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/01_prometheus.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/10_federation.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/rules/00_kube-prometheus.yaml
  tests/kubernetes-1.22.yml
  tests/kubernetes-1.23.yml
Labels: enhancement

#72 Update dependency quay.io/prometheus/prometheus to v2.38.0
  class/defaults.yml
  tests/golden/defaults/rancher-monitoring/rancher-monitoring/01_prometheus.yaml
  tests/golden/kubernetes-1.21/rancher-monitoring/rancher-monitoring/01_prometheus.yaml
Labels: dependency

#65 Update dependency quay.io/prometheus/alertmanager to v0.24.0
  class/defaults.yml
  tests/golden/defaults/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.21/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
Labels: dependency

#83 Fix wrong tests for k8s v1.22 and v1.23
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/01_prometheus.yaml
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/rules/00_kube-prometheus.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/01_prometheus.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/rules/00_kube-prometheus.yaml
  tests/kubernetes-1.22.yml
  tests/kubernetes-1.23.yml
Labels: fix

#82 Replace removed `app` label for alertmanager selector
  component/alertmanager.jsonnet
  docs/modules/ROOT/pages/how-tos/upgrade-4.x-to-5.x.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/defaults/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.21/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.22/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
  tests/golden/kubernetes-1.23/rancher-monitoring/rancher-monitoring/02_alertmanager.yaml
Labels: bug, breaking
